### ISSUE TITLE
Issue in decoder

### ISSUE THREAD

**Issue by alexandrahotti** [deepfindr/gvae#1]
Hi!
Is there an issue here in the decoder? 
Aren't you overwriting the result `x` in the 4th line (and the 6th) when you call `x = self.decoder_dense_2(inputs).relu()`?
I haven't used torch_geometric before, so maybe I am missing something

```
        # Get predictions
        x = self.decoder_dense_1(inputs).relu()
        x = self.decoder_bn_1(x)
        x = self.decoder_dense_2(inputs).relu()
        x = self.decoder_bn_2(x)
        x = self.decoder_dense_3(inputs).relu()
        x = self.decoder_bn_3(x)
        edge_logits = self.decoder_dense_4(x)
```

**Comment by deepfindr** [comment]
Hi! Yes you are right! Thanks for the finding!

This means that the model only used 2 instead of 4 dense layers. Was probably a copy-paste error. But 

I'll push an update in a second :)

**Comment by alexandrahotti** [comment]
Great! 
Really looking forward to the next video :)
